# Quarkus Configuration
quarkus.application.name=avro-checks-quarkus-cli
quarkus.application.version=0.0.1-RC1

# Native image configuration
quarkus.native.additional-build-args=-H:+ReportExceptionStackTraces
quarkus.native.resources.includes=META-INF/**,schemas/**
quarkus.class-loading.parent-first-artifacts=org.apache.avro:avro

# Logging
quarkus.log.level=WARN
quarkus.log.console.enable=false
