# Quarkus Configuration
quarkus.application.name=avro-checks-quarkus-cli
quarkus.application.version=${projectVersion}

# Native image configuration
quarkus.native.enable-all-charsets=true
quarkus.native.additional-build-args=--initialize-at-run-time=org.apache.avro.Schema,-H:+ReportExceptionStackTraces

# Logging
quarkus.log.level=WARN
quarkus.log.console.enable=false
