# Quarkus Configuration
quarkus.application.name=avro-checks-quarkus-cli
quarkus.application.version=0.0.1-RC1

# Native image configuration
quarkus.native.enable-all-charsets=true
quarkus.native.additional-build-args=--initialize-at-run-time=org.apache.avro.Schema --initialize-at-build-time=org.apache.avro.Schema$Parser --initialize-at-build-time=org.apache.avro.Schema$Type --initialize-at-build-time=org.codehaus.jackson.map.ObjectMapper --initialize-at-build-time=org.codehaus.jackson.JsonNode -H:+ReportExceptionStackTraces
quarkus.native.resources.includes=META-INF/**,schemas/**
quarkus.class-loading.parent-first-artifacts=org.apache.avro:avro

# Logging
quarkus.log.level=WARN
quarkus.log.console.enable=false
