# Native Image Configuration for avro-checks-quarkus-cli
Args=--initialize-at-build-time=org.apache.avro.Schema$Parser,org.apache.avro.Schema$Type,org.apache.avro.Schema$Field \
     --initialize-at-run-time=org.apache.avro.Schema \
     -H:+ReportExceptionStackTraces \
     -H:Name=avro-checks
